def show_help():    
    print(
        f"\n"
        f"Task Manager help page\n"
        f"------------------------\n"
        f"Use only lowercase characters.\n"
        f"Descriptions to be enclosed in quotations (single or double).\n"
        f"Priority is one of [high | medium | low | h | m | l].\n\n"
        f"Commands:\n"
        f"list status : Lists all tasks by status under the headers 'Incomplete' and 'Complete'.\n"
        f"  Aliases: List s | l s | ls\n\n"
        f"add [task description] [priority]: Adds a new task.\n"
        f"  Aliases: a [task description] [priority]\n\n"
        f"complete [task id] : marks a task as complete.\n"
        f"  Aliases: c [task id]\n\n"
        f"delete [task id]: Deletes a task.\n"
        f"  Aliases: d [task id]\n\n"
        f"modify [task id] d [new description]: Modifys the task description.\n"
        f"  Aliases: m [task id] d [new description]\n\n"
        f"modify [task id] p [new priority]: Modifys the task priority.\n"
        f"  Aliases: m [task id] p [new description]\n\n"
        f"quit: quits the program.\n"
        f"  Aliases: q\n\n"
        f"help: shows this help file.\n"
        f"  Aliases: h\n"
    )